[package]
name = "btui"
version = "0.1.0"
edition = "2024"

[dependencies]
bluer = { version = "0.17.4", features = ["full"] }
color-eyre = "0.6.5"
dirs = "6.0.0"
futures = "0.3.31"
ratatui = "0.29.0"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
